changelog script in the changelog flow

diff --git a/.github/workflows/changelog.yml b/.github/workflows/changelog.yml
--- a/.github/workflows/changelog.yml
+++ b/.github/workflows/changelog.yml
@@ -20,14 +20,31 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      - name: Checkout flows repo
-        uses: actions/checkout@v4
-        with:
-          repository: 0xMiden/.github
-          ref: feature-reusable-flows
       - name: Check for changes in changelog
         env:
           BASE_REF: ${{ github.event.pull_request.base.ref }}
           NO_CHANGELOG_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'no changelog') }}
-        run: ./scripts/check-changelog.sh "${{ inputs.changelog_path }}"
+          CHANGELOG_FILE_PATH: ${{ inputs.changelog_path }}
+        run: |
+          #!/bin/bash
+          set -uo pipefail
+
+          CHANGELOG_FILE="${CHANGELOG_FILE_PATH:-CHANGELOG.md}"
+
+          if [ "${NO_CHANGELOG_LABEL:-false}" = "true" ]; then
+              # 'no changelog' set, so finish successfully
+              echo "\"no changelog\" label has been set"
+              exit 0
+          else
+              # a changelog check is required
+              # fail if the diff is empty
+              if git diff --exit-code "origin/${BASE_REF}" -- "${CHANGELOG_FILE}"; then
+                  >&2 echo "Changes should come with an entry in the \"CHANGELOG.md\" file. This behavior
+          can be overridden by using the \"no changelog\" label, which is used for changes
+          that are trivial / explicitly stated not to require a changelog entry."
+                  exit 1
+              fi
+
+              echo "The \"CHANGELOG.md\" file has been updated."
+          fi
         shell: bash
